language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --dev

script: vendor/bin/phpunit tests/MY_Model_test.php
